# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ feature/all_in_one_repository ]
  pull_request:
    branches: [ feature/all_in_one_repository ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_frontend:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./kendama-frontend

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: npm dependencies
        run: npm install
      - name: Run Production Build
        run: npm run build
      - name: List directorys
        run: ls -all  
      - name: Upload Frontend Production Build
        uses: actions/upload-artifact@v2
        with:
          name: frontend_artifact
          path: ./kendama-frontend/dist

  build:
    needs: build_frontend
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      with:
        name: frontend_artifact
        path: kendama_backend/frontend_artifact
    
    - name: Display structure of downloaded files
      run: ls -R
    - name: Copy data to public folder
      run: |
       cp -R ./kendama_backend/frontend_artifact/kendama-frontend/. ./kendama_backend/public/
       ls kendama_backend/public